version: '3'

services:
  currency-pairs:
    build: .
    image: currencypairs:latest

    ports:
      - 80:8080

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/currencypairs?useSSL=false
      - SPRING_PROFILES_ACTIVE=prod

    #restart: always

  mysql:
    image: mysql:latest
    ports:
      - 3336:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=currencypairs

    #restart: always

    command: --default-time-zone='+00:00'