spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3336/currencypairs?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

currency:
  historical-zip-url: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.zip

---

debug: true

spring:
  profiles: dev

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        type: trace
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        transaction: DEBUG

        orm:
          jpa: DEBUG

        boot:
          logging:
            ClasspathLoggingApplicationListener: ERROR
          autoconfigure:
            logging:
              AutoConfigurationReportLoggingInitializer: INFO
              ClasspathLoggingApplicationListener: WARN

---

spring:
  profiles: integration

currency:
  historical-zip-url: classpath:eurofxref-hist.zip

---

spring:
  profiles: prod

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true

        order_inserts: true
        order_updates: true

    hibernate:
      ddl-auto: update

  datasource:
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    validation-query: SELECT 1
    validation-query-timeout: 5
